API_KEY = 'your API key'
ENDPOINT_SCHEMA_URL  = 'Schema registry endpoint url'
API_SECRET_KEY = 'API secret key'
BOOTSTRAP_SERVER = 'bootstrap server'
SECURITY_PROTOCOL = 'SASL_SSL'
SSL_MECHANISM = 'PLAIN'
SCHEMA_REGISTRY_API_KEY = 'Schema registry key'
SCHEMA_REGISTRY_API_SECRET = 'Schema registry secret key'


def config_values():
	return API_KEY, ENDPOINT_SCHEMA_URL, API_SECRET_KEY, BOOTSTRAP_SERVER, SECURITY_PROTOCOL, SSL_MECHANISM, SCHEMA_REGISTRY_API_KEY, SCHEMA_REGISTRY_API_SECRET
	
